### ISSUE TITLE
Better error message when passing None as key for FileSystemCaching

### ISSUE THREAD

**Issue by F1nnM** [pallets-eco/cachelib#169]
Accidentally passing None as the key results in the rather mysterious error message:
"UnboundLocalError: local variable 'bkey_hash' referenced before assignment"
thanks to the type check in [_get_filename](https://github.com/pallets-eco/cachelib/blob/0cc195a3eaf06f6031c1b93a6744f240ccfb3a26/src/cachelib/file.py#L198) without an else branch.

A better way to handle this would be to raise an exception "Key must be string, received type [which ever type was received]" or something similar. Thank you!

**Comment by northernSage** [comment]
@F1nnM Thanks for letting us know!
