### ISSUE TITLE
Add new function to fetch all existing cache entries

### ISSUE THREAD

**Issue by momentforever** [pallets-eco/cachelib#191]
## Function

When I use ``FileSystemCache``, I could not find a good way to get all cache info and manage them.

Could please add func which get all cache info and manage them? 

### One Way To Achieving

```python
    def get_all(self) -> _t.Any:
        infos = []
        for fname in self._list_dir():
            print(fname)
            try:
                with self._safe_stream_open(fname, "rb") as f:
                    pickle_time = struct.unpack("I", f.read(4))[0]
                    if pickle_time == 0 or pickle_time >= time():
                        infos.append((fname, self.serializer.load(f)))
            except FileNotFoundError:
                pass
            except (OSError, EOFError, struct.error):
                logging.warning(
                    "Exception raised while handling cache file '%s'",
                    fname,
                    exc_info=True,
                )
        return infos

    def remove_form_fname(self, fname: str) -> None:
        try:
            os.remove(fname)
            self._update_count(delta=-1)
        except FileNotFoundError:
            pass
        except (OSError, EOFError, struct.error):
            logging.warning(
                "Exception raised while handling cache file '%s'",
                fname,
                exc_info=True,
            )
```

It would be nice to provide functions for other cache management methods.

**Comment by northernSage** [comment]
Hey @momentforever, thanks for the suggestion! 

I'm not sure I fully understand your use-case for the requested feature. Could you please elaborate a bit more and provide a few examples of what you mean by "managing the cache info"? 

I see from your example that you are listing the full paths to all `FileSystemCache` underlying cache files. These are already managed by `cachelib` itself under the hood and not meant to be directly deleted/altered by users like that. In fact, I would advise against it since this may cause unexpected behavior.

If what you would like to have is a method to list all existing cache entries, then yeah, I would definitely be willing to add something like that to cachelib's interface.

**Comment by momentforever** [comment]
When I use cachelib in ``Flask Sessions`` by FileSystemCache, cache key hash by client uuid.I wish I could kick out someone's session or view all logged in user's session information by way of admin. However I can't manage all the sessions in one way, because I don't have a good way to store client uuid or cache key.

It's true that it's risky, but I had to manage all the cache in some way.

**Comment by momentforever** [comment]
> Hey @momentforever, thanks for the suggestion!
> 
> I'm not sure I fully understand your use-case for the requested feature. Could you please elaborate a bit more and provide a few examples of what you mean by "managing the cache info"?
> 
> I see from your example that you are listing the full paths to all `FileSystemCache` underlying cache files. These are already managed by `cachelib` itself under the hood and not meant to be directly deleted/altered by users like that. In fact, I would advise against it since this may cause unexpected behavior.
> 
> If what you would like to have is a method to list all existing cache entries, then yeah, I would definitely be willing to add something like that to cachelib's interface.

When I use cachelib in Flask Sessions by FileSystemCache, cache key hash by client uuid. I wish I could kick out someone's session or view all logged in user's session information by way of admin. However I can't manage all the sessions in one way, because I don't have a good way to store client uuid or cache key.

It's true that it's risky, but I had to manage all the cache in some way.

**Comment by ThiefMaster** [comment]
I suggest using a real database for sessions and not just a cache if you need something more fancy than looking up a specific session by ID.

**Comment by momentforever** [comment]
> I suggest using a real database for sessions and not just a cache if you need something more fancy than looking up a specific session by ID.

I agree with your suggestion. However, I have to implement this functionality with zero dependencies include without DB.

**Comment by davidism** [comment]
That's an issue with your requirements then, it's not really enough to justify adding an entire new API.
