### ISSUE TITLE
My project depending on flask-caching throws "no boto3 module found" warning on startup

### ISSUE THREAD

**Issue by tillsteinbach** [pallets-eco/cachelib#215]
How to reproduce:
import flask_caching on any project. Afterwards a warning "no boto3 module found" is shown.

Environment:

- Python version: 3.11.1
- CacheLib version: 0.10.0

**Comment by tillsteinbach** [comment]
It also seems like the logging is reconfigured somehow in a way I don't get logging output from my application anymore. When I change:
```
try:
    import boto3  # type: ignore
    from boto3.dynamodb.conditions import Attr  # type: ignore
except ImportError:
    logging.warning("no boto3 module found")
```
to
try:
    import boto3  # type: ignore
    from boto3.dynamodb.conditions import Attr  # type: ignore
except ImportError:
    pass
```
logging is working again in my application

**Comment by northernSage** [comment]
Hey @tillsteinbach, thanks for letting us know. This is a compatibility issue between flask-caching and latest cachelib release `0.10.0`. I have just released a hotfix pinning flask-caching with cachelib `0.9.0`. Please, upgrade to flask-caching `2.0.2`. Also, make sure you cachlib version is `0.9.0`. I'll update flask-caching to support the latest cachelib with DynamoDb soon, for now this should get it working.

**Comment by tillsteinbach** [comment]
Awesome! Then I can remove my pinning of cachelib again. Thanks for your quick response!

**Comment by fluffy-critter** [comment]
Is there some reason why cachelib is always importing boto3 even if there's no configuration that requires DynamoDB? I'm hoping that the fix for this doesn't involve adding an unnecessary dependency on boto3 in all downstream users of cachelib.

**Comment by RazerM** [comment]
The core issue here has nothing to do with flask-caching, cachelib should not be logging that an optional dependency is missing at `import cachelib` time at all.

It especially shouldn't be doing it using the root logger.

[cachelib/redis.py](https://github.com/pallets-eco/cachelib/blob/main/src/cachelib/redis.py) is already a perfect example of how to handle an optional import.

**Comment by gfvante** [comment]
Thanks all for taking the time to report and bring this to our attention. I'm closing this in favor of #216, since the original issue reported has already been addressed. Also, as I said over at #216, I'll be releasing a hotfix soon
