### ISSUE TITLE
DynamoDb backend is polluting logging handlers

### ISSUE THREAD

**Issue by harpener** [pallets-eco/cachelib#216]
Hi guys,

could you please remove the `logging.warning` logs? It is using a basic configuration which automatically creates undesired logging handlers and causes duplicate logs in projects with their own logging. This issue was here before, but it was conditional, now it happens for everyone who does not have `boto3` library installed.

Replication:

Simply import the library and see handlers in root logger.

Expectation:

There should be no handlers in root logger.

Environment:

- Python version: 3.8.16
- CacheLib version: 0.10.0

Thank you for considering fixing this.

**Comment by gfvante** [comment]
Thanks for letting us know. I'll release a hotfix this weekend 👍

**Comment by senpos** [comment]
Hello!

It seem's like 0.10.1 has dropped to [PyPI](https://pypi.org/project/cachelib/0.10.1/) with the fix, but it is still `Unreleased` on the [Changes](https://cachelib.readthedocs.io/en/stable/changes/) page, and the pollution still happens.
```console
$ mkdir /tmp/iss216 && cd /tmp/iss216
$ virtualenv venv && . venv/bin/activate
$ pip install -U cachelib
Collecting cachelib
  Using cached cachelib-0.10.1-py3-none-any.whl (18 kB)
Installing collected packages: cachelib
Successfully installed cachelib-0.10.1
$ python -c 'import cachelib'
WARNING:root:no boto3 module found
```

I checked sources on both PyPI and GitHub releases, and it looks like [the release on GitHub](https://github.com/pallets-eco/cachelib/releases/tag/0.10.1) has the changes included, but the boto3 import code is **still present** in [PyPI release](https://pypi.org/project/cachelib/0.10.1/#files).

**Comment by northernSage** [comment]
Thanks a lot for letting me know @senpos, just did a new release and checked the files. Everything seems in order now. Could you please double check and let me know if the issue is solved this time? Thanks

**Comment by senpos** [comment]
Yup, it works great now, no warnings were raised if I don't use the new DynamoDB storage!
Thanks!
