### ISSUE TITLE
Pickled integer

### ISSUE THREAD

**Issue by MyrikLD** [pallets-eco/cachelib#72]
Int values pickled in RedisCache
In Redis db it looks like hex string `!\x80\x04\x95\x04\x00\x00\x00\x00\x00\x00\x00M\xC2z.`, not `31426`

Environment:

- Python version: 3.8
- CacheLib version: 0.3.0

**Comment by davidism** [comment]
I don't believe the cache value is supposed to be directly readable. Pickle results in a special bytecode, not plain values.

**Comment by MyrikLD** [comment]
> I don't believe the cache value is supposed to be directly readable. Pickle results in a special bytecode, not plain values.

So, what the matter of `if isinstance(type(value), int):` construction?

**Comment by MyrikLD** [comment]
And this one: https://github.com/MyrikLD/cachelib/blob/f4c8864fbef023d1861c2b9ac712074218a7e614/src/cachelib/redis.py#L80

**Comment by rykroon** [comment]
@davidism @MyrikLD 
I believe the issue with pickled int values for Redis is that it will break increment and decrement since Redis must identify the type of the value to be an int otherwise an exception will be raised.

**Comment by northernSage** [comment]
#147
